# base theme (light, dark, intellij, darcula, maclight or macdark); only used by theme editor
@baseTheme = light
@accentColor = #4C78D8
@background = #f2f2f2

Component.focusColor = @accentColor

Button.arc = 12
Button.hoverBackground = #eeeeee
Button.pressedBackground = #e2e2e2
Button.focusedBorderColor = @accentColor

List.border = @background

ScrollPane.border = @background

TitleBar.background = @background

ProgressBar.arc = 0