# base theme (light, dark, intellij, darcula, maclight or macdark); only used by theme editor
@baseTheme = dark
@accentColor = #4C78D8
@background = #1b1b1b

Component.focusColor = @accentColor

Button.arc = 12
Button.hoverBackground = #5A86E0
Button.pressedBackground = #3F6FD1
Button.focusedBorderColor = @accentColor

List.background = @background
List.border = @background

Panel.background = @background
ScrollPane.background = @background

ScrollPane.border = @background

TitleBar.background = @background

ProgressBar.arc = 0